INSERT INTO country(id,code,name) VALUES(248,'AD','Andorra');
INSERT INTO country(id,code,name) VALUES(2,'AE','United Arab Emirates');
INSERT INTO country(id,code,name) VALUES(3,'AF','Afghanistan');
INSERT INTO country(id,code,name) VALUES(4,'AG','Antigua and Barbuda');
INSERT INTO country(id,code,name) VALUES(5,'AI','Anguilla');
INSERT INTO country(id,code,name) VALUES(6,'AL','Albania');
INSERT INTO country(id,code,name) VALUES(7,'AM','Armenia');
INSERT INTO country(id,code,name) VALUES(8,'AN','Netherlands Antilles');
INSERT INTO country(id,code,name) VALUES(9,'AO','Angola');
INSERT INTO country(id,code,name) VALUES(10,'AQ','Antarctica');
INSERT INTO country(id,code,name) VALUES(11,'AR','Argentina');
INSERT INTO country(id,code,name) VALUES(12,'AS','American Samoa');
INSERT INTO country(id,code,name) VALUES(13,'AT','Austria');
INSERT INTO country(id,code,name) VALUES(14,'AU','Australia');
INSERT INTO country(id,code,name) VALUES(15,'AW','Aruba');
INSERT INTO country(id,code,name) VALUES(16,'AX','Aland Islands');
INSERT INTO country(id,code,name) VALUES(17,'AZ','Azerbaijan');
INSERT INTO country(id,code,name) VALUES(18,'BA','Bosnia and Herzegovina');
INSERT INTO country(id,code,name) VALUES(19,'BB','Barbados');
INSERT INTO country(id,code,name) VALUES(20,'BD','Bangladesh');
INSERT INTO country(id,code,name) VALUES(21,'BE','Belgium');
INSERT INTO country(id,code,name) VALUES(22,'BF','Burkina Faso');
INSERT INTO country(id,code,name) VALUES(23,'BG','Bulgaria');
INSERT INTO country(id,code,name) VALUES(24,'BH','Bahrain');
INSERT INTO country(id,code,name) VALUES(25,'BI','Burundi');
INSERT INTO country(id,code,name) VALUES(26,'BJ','Benin');
INSERT INTO country(id,code,name) VALUES(27,'BL','Saint Barthélemy');
INSERT INTO country(id,code,name) VALUES(28,'BM','Bermuda');
INSERT INTO country(id,code,name) VALUES(29,'BN','Brunei');
INSERT INTO country(id,code,name) VALUES(30,'BO','Bolivia');
INSERT INTO country(id,code,name) VALUES(31,'BR','Brazil');
INSERT INTO country(id,code,name) VALUES(32,'BS','Bahamas');
INSERT INTO country(id,code,name) VALUES(33,'BT','Bhutan');
INSERT INTO country(id,code,name) VALUES(34,'BV','Bouvet Island');
INSERT INTO country(id,code,name) VALUES(35,'BW','Botswana');
INSERT INTO country(id,code,name) VALUES(36,'BY','Belarus');
INSERT INTO country(id,code,name) VALUES(37,'BZ','Belize');
INSERT INTO country(id,code,name) VALUES(38,'CA','Canada');
INSERT INTO country(id,code,name) VALUES(39,'CC','Cocos Islands');
INSERT INTO country(id,code,name) VALUES(40,'CD','Democratic Republic of the Congo');
INSERT INTO country(id,code,name) VALUES(41,'CF','Central African Republic');
INSERT INTO country(id,code,name) VALUES(42,'CG','Republic of the Congo');
INSERT INTO country(id,code,name) VALUES(43,'CH','Switzerland');
INSERT INTO country(id,code,name) VALUES(44,'CI','Ivory Coast');
INSERT INTO country(id,code,name) VALUES(45,'CK','Cook Islands');
INSERT INTO country(id,code,name) VALUES(46,'CL','Chile');
INSERT INTO country(id,code,name) VALUES(47,'CM','Cameroon');
INSERT INTO country(id,code,name) VALUES(48,'CN','China');
INSERT INTO country(id,code,name) VALUES(49,'CO','Colombia');
INSERT INTO country(id,code,name) VALUES(50,'CR','Costa Rica');
INSERT INTO country(id,code,name) VALUES(51,'CU','Cuba');
INSERT INTO country(id,code,name) VALUES(52,'CV','Cape Verde');
INSERT INTO country(id,code,name) VALUES(53,'CX','Christmas Island');
INSERT INTO country(id,code,name) VALUES(54,'CY','Cyprus');
INSERT INTO country(id,code,name) VALUES(55,'CZ','Czech Republic');
INSERT INTO country(id,code,name) VALUES(56,'DE','Germany');
INSERT INTO country(id,code,name) VALUES(57,'DJ','Djibouti');
INSERT INTO country(id,code,name) VALUES(58,'DK','Denmark');
INSERT INTO country(id,code,name) VALUES(59,'DM','Dominica');
INSERT INTO country(id,code,name) VALUES(60,'DO','Dominican Republic');
INSERT INTO country(id,code,name) VALUES(61,'DZ','Algeria');
INSERT INTO country(id,code,name) VALUES(62,'EC','Ecuador');
INSERT INTO country(id,code,name) VALUES(63,'EE','Estonia');
INSERT INTO country(id,code,name) VALUES(64,'EG','Egypt');
INSERT INTO country(id,code,name) VALUES(65,'EH','Western Sahara');
INSERT INTO country(id,code,name) VALUES(66,'ER','Eritrea');
INSERT INTO country(id,code,name) VALUES(67,'ES','Spain');
INSERT INTO country(id,code,name) VALUES(68,'ET','Ethiopia');
INSERT INTO country(id,code,name) VALUES(69,'FI','Finland');
INSERT INTO country(id,code,name) VALUES(70,'FJ','Fiji');
INSERT INTO country(id,code,name) VALUES(71,'FK','Falkland Islands');
INSERT INTO country(id,code,name) VALUES(72,'FM','Micronesia');
INSERT INTO country(id,code,name) VALUES(73,'FO','Faroe Islands');
INSERT INTO country(id,code,name) VALUES(74,'FR','France');
INSERT INTO country(id,code,name) VALUES(75,'GA','Gabon');
INSERT INTO country(id,code,name) VALUES(76,'GB','United Kingdom');
INSERT INTO country(id,code,name) VALUES(77,'GD','Grenada');
INSERT INTO country(id,code,name) VALUES(78,'GE','Georgia');
INSERT INTO country(id,code,name) VALUES(79,'GF','French Guiana');
INSERT INTO country(id,code,name) VALUES(80,'GG','Guernsey');
INSERT INTO country(id,code,name) VALUES(81,'GH','Ghana');
INSERT INTO country(id,code,name) VALUES(82,'GI','Gibraltar');
INSERT INTO country(id,code,name) VALUES(83,'GL','Greenland');
INSERT INTO country(id,code,name) VALUES(84,'GM','Gambia');
INSERT INTO country(id,code,name) VALUES(85,'GN','Guinea');
INSERT INTO country(id,code,name) VALUES(86,'GP','Guadeloupe');
INSERT INTO country(id,code,name) VALUES(87,'GQ','Equatorial Guinea');
INSERT INTO country(id,code,name) VALUES(88,'GR','Greece');
INSERT INTO country(id,code,name) VALUES(89,'GS','South Georgia and the South Sandwich Islands');
INSERT INTO country(id,code,name) VALUES(90,'GT','Guatemala');
INSERT INTO country(id,code,name) VALUES(91,'GU','Guam');
INSERT INTO country(id,code,name) VALUES(92,'GW','Guinea-Bissau');
INSERT INTO country(id,code,name) VALUES(93,'GY','Guyana');
INSERT INTO country(id,code,name) VALUES(94,'HK','Hong Kong');
INSERT INTO country(id,code,name) VALUES(95,'HM','Heard Island and McDonald Islands');
INSERT INTO country(id,code,name) VALUES(96,'HN','Honduras');
INSERT INTO country(id,code,name) VALUES(97,'HR','Croatia');
INSERT INTO country(id,code,name) VALUES(98,'HT','Haiti');
INSERT INTO country(id,code,name) VALUES(99,'HU','Hungary');
INSERT INTO country(id,code,name) VALUES(100,'ID','Indonesia');
INSERT INTO country(id,code,name) VALUES(101,'IE','Ireland');
INSERT INTO country(id,code,name) VALUES(102,'IL','Israel');
INSERT INTO country(id,code,name) VALUES(103,'IM','Isle of Man');
INSERT INTO country(id,code,name) VALUES(104,'IN','India');
INSERT INTO country(id,code,name) VALUES(105,'IO','British Indian Ocean Territory');
INSERT INTO country(id,code,name) VALUES(106,'IQ','Iraq');
INSERT INTO country(id,code,name) VALUES(107,'IR','Iran');
INSERT INTO country(id,code,name) VALUES(108,'IS','Iceland');
INSERT INTO country(id,code,name) VALUES(109,'IT','Italy');
INSERT INTO country(id,code,name) VALUES(110,'JE','Jersey');
INSERT INTO country(id,code,name) VALUES(111,'JM','Jamaica');
INSERT INTO country(id,code,name) VALUES(112,'JO','Jordan');
INSERT INTO country(id,code,name) VALUES(113,'JP','Japan');
INSERT INTO country(id,code,name) VALUES(114,'KE','Kenya');
INSERT INTO country(id,code,name) VALUES(115,'KG','Kyrgyzstan');
INSERT INTO country(id,code,name) VALUES(116,'KH','Cambodia');
INSERT INTO country(id,code,name) VALUES(117,'KI','Kiribati');
INSERT INTO country(id,code,name) VALUES(118,'KM','Comoros');
INSERT INTO country(id,code,name) VALUES(119,'KN','Saint Kitts and Nevis');
INSERT INTO country(id,code,name) VALUES(120,'KP','North Korea');
INSERT INTO country(id,code,name) VALUES(121,'KR','South Korea');
INSERT INTO country(id,code,name) VALUES(122,'KW','Kuwait');
INSERT INTO country(id,code,name) VALUES(123,'KY','Cayman Islands');
INSERT INTO country(id,code,name) VALUES(124,'KZ','Kazakhstan');
INSERT INTO country(id,code,name) VALUES(125,'LA','Laos');
INSERT INTO country(id,code,name) VALUES(126,'LB','Lebanon');
INSERT INTO country(id,code,name) VALUES(127,'LC','Saint Lucia');
INSERT INTO country(id,code,name) VALUES(128,'LI','Liechtenstein');
INSERT INTO country(id,code,name) VALUES(129,'LK','Sri Lanka');
INSERT INTO country(id,code,name) VALUES(130,'LR','Liberia');
INSERT INTO country(id,code,name) VALUES(131,'LS','Lesotho');
INSERT INTO country(id,code,name) VALUES(132,'LT','Lithuania');
INSERT INTO country(id,code,name) VALUES(133,'LU','Luxembourg');
INSERT INTO country(id,code,name) VALUES(134,'LV','Latvia');
INSERT INTO country(id,code,name) VALUES(135,'LY','Libya');
INSERT INTO country(id,code,name) VALUES(136,'MA','Morocco');
INSERT INTO country(id,code,name) VALUES(137,'MC','Monaco');
INSERT INTO country(id,code,name) VALUES(138,'MD','Moldova');
INSERT INTO country(id,code,name) VALUES(139,'ME','Montenegro');
INSERT INTO country(id,code,name) VALUES(140,'MF','Saint Martin');
INSERT INTO country(id,code,name) VALUES(141,'MG','Madagascar');
INSERT INTO country(id,code,name) VALUES(142,'MH','Marshall Islands');
INSERT INTO country(id,code,name) VALUES(143,'MK','Macedonia');
INSERT INTO country(id,code,name) VALUES(144,'ML','Mali');
INSERT INTO country(id,code,name) VALUES(145,'MM','Myanmar');
INSERT INTO country(id,code,name) VALUES(146,'MN','Mongolia');
INSERT INTO country(id,code,name) VALUES(147,'MO','Macao');
INSERT INTO country(id,code,name) VALUES(148,'MP','Northern Mariana Islands');
INSERT INTO country(id,code,name) VALUES(149,'MQ','Martinique');
INSERT INTO country(id,code,name) VALUES(150,'MR','Mauritania');
INSERT INTO country(id,code,name) VALUES(151,'MS','Montserrat');
INSERT INTO country(id,code,name) VALUES(152,'MT','Malta');
INSERT INTO country(id,code,name) VALUES(153,'MU','Mauritius');
INSERT INTO country(id,code,name) VALUES(154,'MV','Maldives');
INSERT INTO country(id,code,name) VALUES(155,'MW','Malawi');
INSERT INTO country(id,code,name) VALUES(156,'MX','Mexico');
INSERT INTO country(id,code,name) VALUES(157,'MY','Malaysia');
INSERT INTO country(id,code,name) VALUES(158,'MZ','Mozambique');
INSERT INTO country(id,code,name) VALUES(159,'NA','Namibia');
INSERT INTO country(id,code,name) VALUES(160,'NC','New Caledonia');
INSERT INTO country(id,code,name) VALUES(161,'NE','Niger');
INSERT INTO country(id,code,name) VALUES(162,'NF','Norfolk Island');
INSERT INTO country(id,code,name) VALUES(163,'NG','Nigeria');
INSERT INTO country(id,code,name) VALUES(164,'NI','Nicaragua');
INSERT INTO country(id,code,name) VALUES(165,'NL','Netherlands');
INSERT INTO country(id,code,name) VALUES(166,'NO','Norway');
INSERT INTO country(id,code,name) VALUES(167,'NP','Nepal');
INSERT INTO country(id,code,name) VALUES(168,'NR','Nauru');
INSERT INTO country(id,code,name) VALUES(169,'NU','Niue');
INSERT INTO country(id,code,name) VALUES(170,'NZ','New Zealand');
INSERT INTO country(id,code,name) VALUES(171,'OM','Oman');
INSERT INTO country(id,code,name) VALUES(172,'PA','Panama');
INSERT INTO country(id,code,name) VALUES(173,'PE','Peru');
INSERT INTO country(id,code,name) VALUES(174,'PF','French Polynesia');
INSERT INTO country(id,code,name) VALUES(175,'PG','Papua New Guinea');
INSERT INTO country(id,code,name) VALUES(176,'PH','Philippines');
INSERT INTO country(id,code,name) VALUES(177,'PK','Pakistan');
INSERT INTO country(id,code,name) VALUES(178,'PL','Poland');
INSERT INTO country(id,code,name) VALUES(179,'PM','Saint Pierre and Miquelon');
INSERT INTO country(id,code,name) VALUES(180,'PN','Pitcairn');
INSERT INTO country(id,code,name) VALUES(181,'PR','Puerto Rico');
INSERT INTO country(id,code,name) VALUES(182,'PS','Palestinian Territory');
INSERT INTO country(id,code,name) VALUES(183,'PT','Portugal');
INSERT INTO country(id,code,name) VALUES(184,'PW','Palau');
INSERT INTO country(id,code,name) VALUES(185,'PY','Paraguay');
INSERT INTO country(id,code,name) VALUES(186,'QA','Qatar');
INSERT INTO country(id,code,name) VALUES(187,'RE','Reunion');
INSERT INTO country(id,code,name) VALUES(188,'RO','Romania');
INSERT INTO country(id,code,name) VALUES(189,'RS','Serbia');
INSERT INTO country(id,code,name) VALUES(190,'RU','Russia');
INSERT INTO country(id,code,name) VALUES(191,'RW','Rwanda');
INSERT INTO country(id,code,name) VALUES(192,'SA','Saudi Arabia');
INSERT INTO country(id,code,name) VALUES(193,'SB','Solomon Islands');
INSERT INTO country(id,code,name) VALUES(194,'SC','Seychelles');
INSERT INTO country(id,code,name) VALUES(195,'SD','Sudan');
INSERT INTO country(id,code,name) VALUES(196,'SE','Sweden');
INSERT INTO country(id,code,name) VALUES(197,'SG','Singapore');
INSERT INTO country(id,code,name) VALUES(198,'SH','Saint Helena');
INSERT INTO country(id,code,name) VALUES(199,'SI','Slovenia');
INSERT INTO country(id,code,name) VALUES(200,'SJ','Svalbard and Jan Mayen');
INSERT INTO country(id,code,name) VALUES(201,'SK','Slovakia');
INSERT INTO country(id,code,name) VALUES(202,'SL','Sierra Leone');
INSERT INTO country(id,code,name) VALUES(203,'SM','San Marino');
INSERT INTO country(id,code,name) VALUES(204,'SN','Senegal');
INSERT INTO country(id,code,name) VALUES(205,'SO','Somalia');
INSERT INTO country(id,code,name) VALUES(206,'SR','Suriname');
INSERT INTO country(id,code,name) VALUES(207,'ST','Sao Tome and Principe');
INSERT INTO country(id,code,name) VALUES(208,'SV','El Salvador');
INSERT INTO country(id,code,name) VALUES(209,'SY','Syria');
INSERT INTO country(id,code,name) VALUES(210,'SZ','Swaziland');
INSERT INTO country(id,code,name) VALUES(211,'TC','Turks and Caicos Islands');
INSERT INTO country(id,code,name) VALUES(212,'TD','Chad');
INSERT INTO country(id,code,name) VALUES(213,'TF','French Southern Territories');
INSERT INTO country(id,code,name) VALUES(214,'TG','Togo');
INSERT INTO country(id,code,name) VALUES(215,'TH','Thailand');
INSERT INTO country(id,code,name) VALUES(216,'TJ','Tajikistan');
INSERT INTO country(id,code,name) VALUES(217,'TK','Tokelau');
INSERT INTO country(id,code,name) VALUES(218,'TL','East Timor');
INSERT INTO country(id,code,name) VALUES(219,'TM','Turkmenistan');
INSERT INTO country(id,code,name) VALUES(220,'TN','Tunisia');
INSERT INTO country(id,code,name) VALUES(221,'TO','Tonga');
INSERT INTO country(id,code,name) VALUES(222,'TR','Turkey');
INSERT INTO country(id,code,name) VALUES(223,'TT','Trinidad and Tobago');
INSERT INTO country(id,code,name) VALUES(224,'TV','Tuvalu');
INSERT INTO country(id,code,name) VALUES(225,'TW','Taiwan');
INSERT INTO country(id,code,name) VALUES(226,'TZ','Tanzania');
INSERT INTO country(id,code,name) VALUES(227,'UA','Ukraine');
INSERT INTO country(id,code,name) VALUES(228,'UG','Uganda');
INSERT INTO country(id,code,name) VALUES(229,'UM','United States Minor Outlying Islands');
INSERT INTO country(id,code,name) VALUES(230,'US','United States');
INSERT INTO country(id,code,name) VALUES(231,'UY','Uruguay');
INSERT INTO country(id,code,name) VALUES(232,'UZ','Uzbekistan');
INSERT INTO country(id,code,name) VALUES(233,'VA','Vatican');
INSERT INTO country(id,code,name) VALUES(234,'VC','Saint Vincent and the Grenadines');
INSERT INTO country(id,code,name) VALUES(235,'VE','Venezuela');
INSERT INTO country(id,code,name) VALUES(236,'VG','British Virgin Islands');
INSERT INTO country(id,code,name) VALUES(237,'VI','U.S. Virgin Islands');
INSERT INTO country(id,code,name) VALUES(238,'VN','Vietnam');
INSERT INTO country(id,code,name) VALUES(239,'VU','Vanuatu');
INSERT INTO country(id,code,name) VALUES(240,'WF','Wallis and Futuna');
INSERT INTO country(id,code,name) VALUES(241,'WS','Samoa');
INSERT INTO country(id,code,name) VALUES(242,'YE','Yemen');
INSERT INTO country(id,code,name) VALUES(243,'YT','Mayotte');
INSERT INTO country(id,code,name) VALUES(244,'ZA','South Africa');
INSERT INTO country(id,code,name) VALUES(245,'ZM','Zambia');
INSERT INTO country(id,code,name) VALUES(246,'ZW','Zimbabwe');
INSERT INTO country(id,code,name) VALUES(247,'CS','Serbia and Montenegro');

insert into vegetationtype(vegetationtype) values ('Evergreen needleleaf');
insert into vegetationtype(vegetationtype) values ('Evergreen broadleaf');
insert into vegetationtype(vegetationtype) values ('Deciduous needleleaf');
insert into vegetationtype(vegetationtype) values ('Deciduous broadleaf');
insert into vegetationtype(vegetationtype) values ('Mixed forest');
insert into vegetationtype(vegetationtype) values ('Closed shrubland');
insert into vegetationtype(vegetationtype) values ('Open shrubland');
insert into vegetationtype(vegetationtype) values ('Woody savanna');
insert into vegetationtype(vegetationtype) values ('Savanna');
insert into vegetationtype(vegetationtype) values ('Grassland');
insert into vegetationtype(vegetationtype) values ('Permanent wetland');
insert into vegetationtype(vegetationtype) values ('Cropland');
insert into vegetationtype(vegetationtype) values ('Urban');
insert into vegetationtype(vegetationtype) values ('Cropland / natural vegetation mosaic');
insert into vegetationtype(vegetationtype) values ('Snow / ice landscape');
insert into vegetationtype(vegetationtype) values ('Barren / sparsely vegetated');
insert into vegetationtype(vegetationtype) values ('Water bodies');

insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(11,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleNEE.R','ModelAnnualCycleNEE','MODEL_OUTPUT','AnnualCycle','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(12,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleQg.R','ModelAnnualCycleQg','MODEL_OUTPUT','AnnualCycle','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(13,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleQh.R','ModelAnnualCycleQh','MODEL_OUTPUT','AnnualCycle','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(14,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleQle.R','ModelAnnualCycleQle','MODEL_OUTPUT','AnnualCycle','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(15,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleRnet.R','ModelAnnualCycleRnet','MODEL_OUTPUT','AnnualCycle','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(16,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAnnualCycleSWnet.R','ModelAnnualCycleSWnet','MODEL_OUTPUT','AnnualCycle','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(17,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowNEE.R','ModelAvWindowNEE','MODEL_OUTPUT','AvWindow','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(18,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowQg.R','ModelAvWindowQg','MODEL_OUTPUT','AvWindow','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(19,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowQh.R','ModelAvWindowQh','MODEL_OUTPUT','AvWindow','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(20,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowQle.R','ModelAvWindowQle','MODEL_OUTPUT','AvWindow','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(21,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowRnet.R','ModelAvWindowRnet','MODEL_OUTPUT','AvWindow','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(22,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelAvWindowSWnet.R','ModelAvWindowSWnet','MODEL_OUTPUT','AvWindow','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(23,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelConserve.R','ModelConserve','MODEL_OUTPUT','Conserve','ALL');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(24,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleNEE.R','ModelDiurnalCycleNEE','MODEL_OUTPUT','DiurnalCycle','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(25,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleQg.R','ModelDiurnalCycleQg','MODEL_OUTPUT','DiurnalCycle','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(26,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleQh.R','ModelDiurnalCycleQh','MODEL_OUTPUT','DiurnalCycle','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(27,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleQle.R','ModelDiurnalCycleQle','MODEL_OUTPUT','DiurnalCycle','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(28,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleRnet.R','ModelDiurnalCycleRnet','MODEL_OUTPUT','DiurnalCycle','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(29,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelDiurnalCycleSWnet.R','ModelDiurnalCycleSWnet','MODEL_OUTPUT','DiurnalCycle','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(30,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelEvapFrac.R','ModelEvapFrac','MODEL_OUTPUT','EvapFrac','ALL');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(31,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfNEE.R','ModelPdfNEE','MODEL_OUTPUT','Pdf','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(32,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfQg.R','ModelPdfQg','MODEL_OUTPUT','Pdf','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(33,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfQh.R','ModelPdfQh','MODEL_OUTPUT','Pdf','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(34,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfQle.R','ModelPdfQle','MODEL_OUTPUT','Pdf','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(35,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfRnet.R','ModelPdfRnet','MODEL_OUTPUT','Pdf','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(36,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelPdfSWnet.R','ModelPdfSWnet','MODEL_OUTPUT','Pdf','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(37,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterNEE.R','ModelScatterNEE','MODEL_OUTPUT','Scatter','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(38,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterQg.R','ModelScatterQg','MODEL_OUTPUT','Scatter','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(39,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterQh.R','ModelScatterQh','MODEL_OUTPUT','Scatter','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(40,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterQle.R','ModelScatterQle','MODEL_OUTPUT','Scatter','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(41,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterRnet.R','ModelScatterRnet','MODEL_OUTPUT','Scatter','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(42,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelScatterSWnet.R','ModelScatterSWnet','MODEL_OUTPUT','Scatter','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(43,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorNEE.R','ModelTaylorNEE','MODEL_OUTPUT','Taylor','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(44,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorQg.R','ModelTaylorQg','MODEL_OUTPUT','Taylor','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(45,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorQh.R','ModelTaylorQh','MODEL_OUTPUT','Taylor','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(46,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorQle.R','ModelTaylorQle','MODEL_OUTPUT','Taylor','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(47,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorRnet.R','ModelTaylorRnet','MODEL_OUTPUT','Taylor','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(48,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTaylorSWnet.R','ModelTaylorSWnet','MODEL_OUTPUT','Taylor','SWnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(49,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesNEE.R','ModelTimeseriesNEE','MODEL_OUTPUT','Timeseries','NEE');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(50,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesQg.R','ModelTimeseriesQg','MODEL_OUTPUT','Timeseries','Qg');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(51,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesQh.R','ModelTimeseriesQh','MODEL_OUTPUT','Timeseries','Qh');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(52,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesQle.R','ModelTimeseriesQle','MODEL_OUTPUT','Timeseries','Qle');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(53,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesRnet.R','ModelTimeseriesRnet','MODEL_OUTPUT','Timeseries','Rnet');
insert into analysistype(id,executablepath,name,type,analysistypename,variablename) values(54,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ModelTimeseriesSWnet.R','ModelTimeseriesSWnet','MODEL_OUTPUT','Timeseries','SWnet');

insert into analysistype(id,executablepath,name,type) values(1,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleNEE.R','ObsAnnualCycleNEE','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(2,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleQg.R','ObsAnnualCycleQg','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(3,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleQh.R','ObsAnnualCycleQh','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(4,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleQle.R','ObsAnnualCycleQle','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(5,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleRnet.R','ObsAnnualCycleRnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(6,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsAnnualCycleSWnet.R','ObsAnnualCycleSWnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(7,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsConserve.R','ObsConserve','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(8,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleNEE.R','ObsDiurnalCycleNEE','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(9,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleQg.R','ObsDiurnalCycleQg','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(10,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleQh.R','ObsDiurnalCycleQh','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(55,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleQle.R','ObsDiurnalCycleQle','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(56,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleRnet.R','ObsDiurnalCycleRnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(57,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsDiurnalCycleSWnet.R','ObsDiurnalCycleSWnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(58,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsEvapFrac.R','ObsEvapFrac','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(59,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfNEE.R','ObsPdfNEE','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(60,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfQg.R','ObsPdfQg','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(61,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfQh.R','ObsPdfQh','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(62,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfQle.R','ObsPdfQle','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(63,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfRnet.R','ObsPdfRnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(64,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsPdfSWnet.R','ObsPdfSWnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(65,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesNEE.R','ObsTimeseriesNEE','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(66,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesQg.R','ObsTimeseriesQg','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(67,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesQh.R','ObsTimeseriesQh','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(68,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesQle.R','ObsTimeseriesQle','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(69,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesRnet.R','ObsTimeseriesRnet','DATA_SET_VERSION');
insert into analysistype(id,executablepath,name,type) values(70,'/opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/rWrapper -f /opt/tomcat/6.0.20/sites/pals.unsw.edu.au/pals/r/ObsTimeseriesSWnet.R','ObsTimeseriesSWnet','DATA_SET_VERSION');

update analysistype set analysistypename='ObsAnnualCycle' where id >= 1 and id <= 6;
update analysistype set analysistypename='ObsConserve' where id = 7;
update analysistype set analysistypename='ObsDiurnalCycle' where id >= 8 and id <= 10;
update analysistype set analysistypename='ObsDiurnalCycle' where id >= 55 and id <= 57;
update analysistype set analysistypename='ObsEvapFrac' where id = 58;
update analysistype set analysistypename='ObsPdf' where id >= 59 and id <= 64;
update analysistype set analysistypename='ObsDiurnalCycle' where id >= 65 and id <= 70;

update analysistype set variablename='NEE' where id=1 or id=8 or id=59 or id=65;
update analysistype set variablename='Qg' where id=2 or id=9 or id=60 or id=66;
update analysistype set variablename='Qh' where id=3 or id=10 or id=61 or id=67;
update analysistype set variablename='Qle' where id=4 or id=55 or id=62 or id=68;
update analysistype set variablename='Rnet' where id=5 or id=56 or id=63 or id=69;
update analysistype set variablename='SWnet' where id=6 or id=57 or id=64 or id=70;
update analysistype set variablename='ALL' where id=7 or id=58;