#!/bin/bash
#export DISPLAY=:9.0
#source /etc/profile.d/modules.sh 
#module add R
export R_LIBS_USER=/root/workspace
export LD_LIBRARY_PATH=/usr/local/lib
R --slave $@
# Somehow only two command options work. The third is interpreted as a file name for some reason
# R recommends to use: Rscript --vanilla --no-save --slave xyz.R arg1 arg2 arg3